[
build-system
]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[
project
]
name = "credmodex"
version = "0.1.0"
description = "A Python library for credit risk modeling"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name="Your Name", email="your@email.com" }]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "plotly",
    "scipy"
]